{% set name = "torchio" %}
{% set version = "0.19.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4f770f07cb06a380bfc45beaf25714937c8faa86896b1a666b5752ec76c57ca

build:
  number: 0
  noarch: python
  entry_points:
    - torchio-transform=torchio.cli.apply_transform:main
    - tiohd=torchio.cli.print_info:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6, <3.13
  run:
    - click
    - deprecated >=1.2.5
    - humanize
    - nibabel
    - numpy
    - python >=3.6, <3.13
    - scipy
    - simpleitk !=2.0.*
    - pytorch >=1.7
    - tqdm
    - setuptools

test:
  imports:
    - torchio

about:
  home: https://github.com/fepegar/torchio
  summary: Tools for loading, augmenting and writing 3D medical images on PyTorch.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://torchio.readthedocs.io/index.html

extra:
  recipe-maintainers:
    - sarthakpati # https://github.com/fepegar/torchio/discussions/480#discussioncomment-455823
