{% set name = "torchio" %}
{% set version = "0.18.30" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 02d748f3a4cf16700d973e2dc08208d81a07d1935a8549b6a7307e07a106c21f

build:
  number: 0
  noarch: python
  entry_points:
    - torchio-transform=torchio.cli.apply_transform:main
    - tiohd=torchio.cli.print_info:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - deprecated
    - humanize
    - nibabel
    - numpy
    - python >=3.6
    - scipy
    - simpleitk <2
    - pytorch
    - tqdm
    - setuptools

test:
  imports:
    - torchio

about:
  home: https://github.com/fepegar/torchio
  summary: Tools for loading, augmenting and writing 3D medical images on PyTorch.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://torchio.readthedocs.io/index.html

extra:
  recipe-maintainers:
    - sarthakpati # https://github.com/fepegar/torchio/discussions/480#discussioncomment-455823
